Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Models/BaiTap.cs
namespace DOANTOTNGHIEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("BaiTap")]
    public partial class BaiTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiTap()
        {
            BaiTapTLs = new HashSet<BaiTapTL>();
            BaiTapTNs = new HashSet<BaiTapTN>();
            CauHois = new HashSet<CauHoi>();
            FileBTTLs = new HashSet<FileBTTL>();
            ThongBaos = new HashSet<ThongBao>();
        }

        [Key]
        public long MaBaiTap { get; set; }

        [StringLength(2000)]
        public string ChuDe { get; set; }

        [StringLength(20)]
        public string LoaiBaiTap { get; set; }

        public DateTime? ThoiGianDang { get; set; }

        public DateTime? ThoiGianKetThuc { get; set; }

        public long? MaLop { get; set; }

        [StringLength(20)]
        public string NguoiTao { get; set; }

        public string Thongtin { get; set; }

        public virtual LopHoc LopHoc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTapTL> BaiTapTLs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTapTN> BaiTapTNs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHoi> CauHois { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileBTTL> FileBTTLs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Models/Diem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DOANTOTNGHIEP.Models
{
    public class Diem
    {
        public string taikhoan { get; set; }
        public string Hoten { get; set; }
        public string email { get; set; }
        public string anh { get; set; }
        public long? diem { get; set; }
        public int soluongbaicodiem { get; set; }
        public int soluongbaitap { get; set; }
        public int soluongtre { get; set; }
        public int soluongchuanop { get; set; }
        public DateTime  ngaythamgia { get; set; }

    }
 
}

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Models/Kiemtradaovan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DOANTOTNGHIEP.Models
{
    public class Kiemtradaovan
    {
        public double? Percents { get; set; }
        public TTBaiTapTL Tailieu1 { get; set; }
        public TTBaiTapTL Tailieu2 { get; set; }

    }
}

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Models/Mess.cs
namespace DOANTOTNGHIEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Mess")]
    public partial class Mess
    {
        [Key]
        public long Ma { get; set; }

        [StringLength(20)]
        public string NguoiGui { get; set; }

        [StringLength(20)]
        public string NguoiNhan { get; set; }

        public long? malop { get; set; }

        public string TinNhan { get; set; }

        public DateTime? thoigiangui { get; set; }

        public virtual LopHoc LopHoc { get; set; }

        public virtual TaiKhoan TaiKhoan { get; set; }

        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DOANTOTNGHIEP.Models;
using Spire.Doc;
using Spire.Doc.Documents;
using Spire.Doc.Fields;
using Spire.Doc.Fields.OMath;
using Spire.Pdf;
using Spire.Pdf.Graphics;
using Spire.Pdf.Tables;
using Spire.Xls;
using System.Data;
using System.Drawing;
using System.IO;
using System.Net;
using System.Text;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
namespace DOANTOTNGHIEP.Controllers
{
    public class ClassController : Controller
    {



        
        DB db = new DB();
        public void checkcookieuser()
        {
            DB db = new DB();
            var user = Request.Cookies["user"];
            if (user != null && user["TenDangNhap"].ToString().Length > 0 && user["Matkhau"].ToString().Length > 0)
            {
                var tendangnhap = Models.crypt.Encrypt.Decryptuser(user["TenDangNhap"].ToString());
                var matkhau = user["Matkhau"].ToString();
                var TK = db.TaiKhoans.SingleOrDefault(x => x.TenDangNhap.Equals(tendangnhap) && x.MatKhau.Equals(matkhau));
                if (TK != null)
                {
                    Session["user"] = TK;
                }

            }
        }
        public string getsession()
        {
            //checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            return user.TenDangNhap;

        }

        // GET: Class
        //hien thong báo 
        public ActionResult Index(string id)
        {
            checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            if (user == null) return RedirectToAction("Login", "Login");
            var lop = db.ThanhVienLops.SingleOrDefault(x => x.MaLop.ToString().Equals(id) && x.Mathanhvien.Equals(user.TenDangNhap));
            if (lop == null)
            {
                return RedirectToAction("Index", "TrangChu");
            }

            if (id != null)
            {
                Session["malop"] = id;

            }
            else
            {
                if (Session["malop"] == null)
                {
                    return RedirectToAction("Index", "TrangChu");
                }
                id = Session["malop"].ToString();
            }


            var thongbao = db.ThongBaos.Where(x => x.MaLop.ToString().Equals(id)).OrderByDescending(y => y.NgayDang).ToList();
            Session["lophoc"] = db.LopHocs.SingleOrDefault(x => x.MaLop.ToString().Equals(id));

            return View(thongbao);
        }
        [HttpPost]
        //tham gia lop hoc
        public ActionResult checkclass()
        {
            checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            if (user == null) return RedirectToAction("Login", "Login");
            string nguoitao = user.TenDangNhap;
            string id = Request.Form["maclassid"];
            string ma = Models.crypt.Encrypt.Decryptclass(id).ToString();


            if (ModelState.IsValid)
            {
                DB db = new DB();
                var TK = db.LopHocs.SingleOrDefault(x => x.MaLop.ToString().Equals(ma));
                if (TK != null)
                {
                    if (db.ThanhVienLops.SingleOrDefault(x => x.MaLop.ToString().Equals(ma) && x.Mathanhvien.Equals(nguoitao)) != null)
                    {
                        ModelState.AddModelError("ErrorJoinClass", "Lop đã tham gia ");
                        return View("JoinClass");
                    }
                    ThanhVienLop tvl = new ThanhVienLop();
                    tvl.MaLop = Convert.ToInt32(ma);
                    tvl.Mathanhvien = nguoitao;
                    tvl.NgayThamGia = DateTime.Now;
                    db.ThanhVienLops.Add(tvl);
                    db.SaveChanges();
                    var baitap = db.BaiTaps.Where(x => x.MaLop.ToString().Equals(ma)).ToList();
                    foreach (var bai in baitap)
                    {
                        if (bai.LoaiBaiTap.Equals("TracNghiem"))
                        {
                            BaiTapTN btn = new BaiTapTN();
                            btn.MaBaiTap = bai.MaBaiTap;
                            btn.NguoiNop = nguoitao;
                            db.BaiTapTNs.Add(btn);
                            db.SaveChanges();
                        }
                        else if (bai.LoaiBaiTap.Equals("TuLuan"))
                        {
                            BaiTapTL btl = new BaiTapTL();
                            btl.MaBaiTap = bai.MaBaiTap;
                            btl.NguoiNop = nguoitao;
                            db.BaiTapTLs.Add(btl);
                            db.SaveChanges();
                        }
                    }
                    return RedirectToAction("Index", "TrangChu");
                }
                else
                {
                    ModelState.AddModelError("ErrorJoinClass", "Lop khong ton  tai ");
                }


            }
            return View("JoinClass");
        }
        public void CreateFolder(string strPath)
        {
            try
            {
                if (Directory.Exists(strPath) == false)
                {
                    Directory.CreateDirectory(strPath);
                }
            }
            catch { }
        }
        [HttpPost]
        //tao lop hoc
        public ActionResult createclass()
        {
            checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            if (user == null) return RedirectToAction("Login", "Login");
            string nguoitao = user.TenDangNhap;
            string name = Request.Form["classname"];
            string infor = Request.Form["inforclass"];


            DB db = new DB();

            if (name != null && infor != null)
            {


                LopHoc lp = new LopHoc();
                lp.TenLop = name;
                lp.ThongTinLopHoc = infor;
                lp.NguoiTao = nguoitao;
                lp.NgayTao = DateTime.Now;
                lp.Hinhanh = "/Content/image/imageclass/img_backtoschool.jpg";
                db.LopHocs.Add(lp);
                db.SaveChanges();
                CreateFolder(Server.MapPath("~/Content/document/" + Models.crypt.Encrypt.encryptfoder(lp.MaLop.ToString()).Replace("+","").Replace("=", "").Replace("-", "").Replace("_", "")));
                ThanhVienLop tvl = new ThanhVienLop();
                tvl.MaLop = lp.MaLop;
                tvl.Mathanhvien = nguoitao;
                tvl.NgayThamGia = DateTime.Now;
                db.ThanhVienLops.Add(tvl);
                db.SaveChanges();
                CreateFolder(Server.MapPath("~/Content/document/" + Models.crypt.Encrypt.encryptfoder(lp.MaLop.ToString()).Replace("+", "").Replace("=", "").Replace("-", "").Replace("_", "") + "/"+ Models.crypt.Encrypt.encryptfoder(tvl.Mathanhvien).Replace("+", "").Replace("=", "").Replace("-", "").Replace("_", "")));
                return RedirectToAction("Index", "TrangChu");
            }

            return RedirectToAction("Index", "TrangChu");
        }
        [HttpGet]
        public ActionResult Editclass()
        {
            checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            if (user == null) return RedirectToAction("Login", "Login");
            string nguoitao = user.TenDangNhap;
            if (Session["lophoc"] == null) return RedirectToAction("Index", "TrangChu");
            string malop = Session["malop"].ToString();
            var lop = db.LopHocs.SingleOrDefault(x => x.MaLop.ToString().Equals(malop) && x.NguoiTao.Equals(user.TenDangNhap));
            if (lop == null)
            {
                return RedirectToAction("Index", "TrangChu");
            }

            var lophoc = Session["lophoc"] as DOANTOTNGHIEP.Models.LopHoc;
            return View(lophoc);
        }

        [HttpPost]
        public ActionResult Checkeditclass(LopHoc s, HttpPostedFileBase file)
        {
            checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            if (user == null) return RedirectToAction("Login", "Login");
            string nguoitao = user.TenDangNhap;
            var lophoc = Session["lophoc"] as DOANTOTNGHIEP.Models.LopHoc;
            var lop = db.LopHocs.SingleOrDefault(x => x.MaLop.ToString().Equals(lophoc.MaLop.ToString()) && x.NguoiTao.Equals(nguoitao));
            if (lop == null) return Index(lophoc.MaLop.ToString());
            lop.TenLop = s.TenLop;
            lop.ThongTinLopHoc = s.ThongTinLopHoc;
            if (file != null)
            {

                string path = Server.MapPath("~/Content/image/imageclass/" + lop.MaLop + file.FileName);

                lop.Hinhanh = "/Content/image/imageclass/" + lop.MaLop + file.FileName;

                file.SaveAs(path);
            }
            db.SaveChanges();

            return RedirectToAction("Index", new { id = lophoc.MaLop.ToString() });

        }


        //diem
        public ActionResult Diem(string id)
        {
            checkcookieuser();
            var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
            if (user == null) return RedirectToAction("Login", "Login");

            Session["malop"] = id;

            var lop = db.ThanhVienLops.SingleOrDefault(x => x.MaLop.ToString().Equals(id) && x.Mathanhvien.Equals(user.TenDangNhap));

            if (lop == null)
            {
                return RedirectToAction("Index", "TrangChu");
            }
            var malop = Session["malop"].ToString();
            string nguoitao = user.TenDangNhap;
            var diem = DOANTOTNGHIEP.Models.GetData.Getdiem.danhsachdiem(malop, nguoitao);
            ViewBag.excel = exceldsdiem(diem);
            ViewBag.pdf = pdfdsdiem(diem);
            return View(diem);

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Views/Class/AddClass.cshtml
@{
   
    
}

<style>
    .frameclass {
        width: 100%;
        height: 100%;
        position: fixed;
        display: block;
        margin-top: -20px;
        background-size: cover;
    }

    .createclass {
        position: relative;
        text-align: left;
        border: 0px solid #000000;
        width: 500px;
        height: auto;
        background: #5858FA;
        background-color: white;
        padding: 40px;
        border-radius: 5px;
        margin: 10% auto;
        display: block;
        box-shadow: 10px 10px 10px rgb(0 0 0 / 20%);
    }

    textarea {
        border-radius: 5px;
        resize: none;
        outline: none;
        width: 400px;
        max-width: 500px;
        height: 100px;
        border: 1px solid #A9A9A9;
        padding: 12px 40px 12px 20px;
    }

    .glyphicon-remove-circle:hover {
        background-color: black;
        border-radius: 10px;
    }

    .addclass {
        margin-top: 20px;
        border-radius: 50px;
        background-image: linear-gradient(60deg, #5858FA, #081C46);
        padding-right: 20px;
        padding-left: 20px
    }

    .divaddclass {
        background-image: linear-gradient(60deg, #5858FA, #081C46);
        position: relative;
        width: 90%;
        right: 20px;
        left: 20px;
        top: -70px;
        border-radius: 5px;
        text-align: left;
        padding: 20px
    }

    textarea::placeholder {
        color: black;
    }

    textarea:focus, textarea:focus::placeholder, textarea:focus + i {
        color: #ff1464;
    }
</style>
<div class="frameclass">
  >
    <div class="createclass">

        @using (Html.BeginForm("createclass", "Class", FormMethod.Post))
        {
            <div class="divaddclass"><label style="color:white">Add Class</label><br /></div>



            <div class="form-group bmd-form-group" style="margin-top:-20px">
                <label class="bmd-label-floating" style="color:white;">Class Name</label><br />
                <textarea name="classname" required placeholder="Nhập tên lớp" ></textarea>

            </div>
            <div class="form-group bmd-form-group">
                <label class="bmd-label-floating" style="color:white;">Class Infro</label><br />
                <textarea name="inforclass" required placeholder="Nhập thông tin lớp"></textarea>
            </div>


            <div class="form-group bmd-form-group">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>


        }

    </div>

</div>

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Views/Class/BaiTap.cshtml
@model List<DOANTOTNGHIEP.Models.BaiTap>
@{

    ViewData["Title"] = "Bài tập HS";
    Layout = "~/Views/Shared/Layoutclass.cshtml";
    var lophoc = Session["lophoc"] as DOANTOTNGHIEP.Models.LopHoc;
    var user = Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan;
    string nguoitao = user.TenDangNhap;
    DOANTOTNGHIEP.Models.ThongBao tb = new DOANTOTNGHIEP.Models.ThongBao();
    var malop = Session["malop"].ToString();
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <style>
        .thongbaomoi {
            display: none;
            border-radius: 10px;
            background-image: linear-gradient(to left, #1A6EFF, pink);
            text-align: center;
            width: 10%;
            margin: 5px auto;
            position: fixed;
            right: 10px;
            left: 10px;
            z-index: 9999;
        }



        .divbaitap {
            width: 100%;
            border: 0px solid black;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 10px;
            background-color: white;
            box-shadow: 10px 5px 5px rgb(0 0 0 / 20%);
        }

        .divfilebaitap {
            padding: 10px;
            border: 0px solid black;
            border-radius: 5px;
            margin-left: 20px;
            width: fit-content;
            margin-bottom: 5px
        }

        .imgfilebaitap {
            background-color: transparent;
            border: 0px;
            background-size: cover
        }

        .ngayhethanbaitap {
            font-size: 10px;
            float: right;
            margin-left: 80%;
        }

    </style>
    <script type="text/javascript">

        $(document).ready(function () {
            reset();
            $('.headbaitap').css("color", "black");
            $('.headbaitap').css("background-color", "white");

            $("#anthongbaomoi").click(function () {
                
                $(".thongbaomoi").css("display", "none");
            });
        });

        $(function () {
            var baitap = $.connection.chat;

            baitap.client.baitap = function (malop) {
               
                if (  malop == "@lophoc.MaLop") {
                    $(".thongbaomoi").css("display", "block");

                }

            };

        });






    </script>
</head>
<body class="container" style="background-color: white; margin-top: 20px">
    <div class="thongbaomoi">
        <label>Bai tap moi</label><br />
        <a href="~/Class/BaiTap/@malop">Làm mới</a>
        <a id="anthongbaomoi" href="#">Huy</a>
    </div>

    @if (Model != null)
    {

        {

            int baichuanop = 0;
            int baidanop = 0;
            int bainopmuon = 0;
            foreach (var i in Model)
            {

                if (i.LoaiBaiTap.Equals("TuLuan"))
                {

                    var y = i.BaiTapTLs.SingleOrDefault(x => x.MaBaiTap.Equals(i.MaBaiTap) && x.NguoiNop.Equals((Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan).TenDangNhap));
                    if (y != null)
                    {

                        if (y.Trangthai == null)
                        {

                            if (y.NgayNop == null)
                            {
                                baichuanop++;
                            }

                        }
                        else if (y.Trangthai != null)
                        {

                            if (y.NgayNop != null)
                            {
                                baidanop++;
                            }


                        }

                        if (y.NgayNop != null)
                        {
                            if (y.NgayNop > i.ThoiGianKetThuc)
                            {
                                bainopmuon++;
                            }

                        }



                    }

                }
                else if (i.LoaiBaiTap.Equals("TracNghiem"))
                {
                    var y = i.BaiTapTNs.SingleOrDefault(x => x.MaBaiTap.Equals(i.MaBaiTap) && x.NguoiNop.Equals((Session["user"] as DOANTOTNGHIEP.Models.TaiKhoan).TenDangNhap));
                    if (y != null)
                    {


                        if (y.NgayNop == null)
                        {
                            baichuanop++;
                        }





                        if (y.NgayNop != null)
                        {
                            baidanop++;
                            if (y.NgayNop > i.ThoiGianKetThuc)
                            {
                                bainopmuon++;
                            }

                        }

                    }

                }
            }

            <div class="row container-fluid">
                <div class="col-md-2"></div>
                <div class="col-md-3" style="margin:0px auto;display:block">

                    <div>
                        <a href="~/Class/Bainop">
                            <div style="padding:20px;background-color:aquamarine;border-radius:20px;width:200px;color:black">

                                <div><label>Bài đã nộp</label></div>
                                <div>@baidanop</div>
                            </div>
                        </a>

                    </div>
                </div>
                <div class="col-md-3 " style="margin:0px auto;display:block">

                    <div>
                        <a href="~/Class/Baichuanop">
                            <div style="padding:20px;background-color:cornflowerblue;border-radius:20px;width:200px;color:black">

                                <div><label>Bài chưa nộp</label></div>
                                <div>@baichuanop</div>
                            </div>
                        </a>
                    </div>

                </div>
                <div class="col-md-3 ">
                    <div>
                        <a href="~/Class/Bainopmuon">
                            <div style="padding:20px;background-color:orangered;border-radius:20px;width:200px;color:black">

                                <div><label>Bài Nộp muộn </label></div>
                                <div>@bainopmuon</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>








        }


    }
    <div style="clear:left;margin-top:30px">




        @{


            if (Model != null)
            {
                foreach (var i in Model)
                {

                    <a href="~/Class/ShowInforBaiTap/@i.MaBaiTap">
                        <div class="divbaitap">
                            <table style="margin-bottom:20px;">
                                <tr>
                                    <th><img class="navbar-link" src=@i.LopHoc.TaiKhoan.HinhAnh width="40" height="40" style="border-radius:45px;" /></th>
                                    <th style="padding-left:10px;width:100%">
                                        <label style="font-size:20px;">Chủ đề:@i.ChuDe</label><br />
                                        <label style="font-size:10px;">@i.ThoiGianDang.Value.ToString(string.Format("HH:mm dd/MM/yyyy")) ~ @i.ThoiGianKetThuc.Value.ToString(string.Format("HH:mm dd/MM/yyyy"))</label>
                                        
                                    </th>
                                </tr>
                            </table>
                            <hr />
                            <div>@Html.Raw(@i.Thongtin)</div><br />
                            @{
                                foreach (var filetb in i.FileBTTLs)
                                {
                                    if (@filetb.TenFile.IndexOf(".png") == @filetb.TenFile.Length - 4 || @filetb.TenFile.IndexOf(".jpg") == @filetb.TenFile.Length - 4)
                                    {
                                        <div class="divfilebaitap">
                                            <img class="imgfilebaitap" src="@filetb.NoiLuu" width="50" height="30">
                                            <a href="@filetb.NoiLuu"  download>@filetb.TenFile</a>
                                        </div>

                                    }
                                    else
                                    {


                                        <div class="divfilebaitap">
                                            <img class="imgfilebaitap" src="~/Content/image/Icon/unnamed.png" width="40" height="30">
                                            <a href="@filetb.NoiLuu" download style="margin-left:20px">@filetb.TenFile</a>
                                        </div> }
                                }
                            }




                        </div>
                    </a>
                }
            }
        }








    </div>
</body>
</html>

Chuongtrinh/DOANTOTNGHIEP/DOANTOTNGHIEP/Views/Class/Editclass.cshtml
@model  DOANTOTNGHIEP.Models.LopHoc
@{

    ViewData["Title"] = "Edit class";
    Layout = "~/Views/Shared/Layoutclass.cshtml";
    
}
<style type="text/css">


    .frameaccount {
        width: 100%;
        height: 100%;
        position: fixed;
        display: block;
        background-size:cover;
        margin-top: -20px;
    }

    .account {
        position: relative;
        text-align: left;
        border: 0px solid #000000;
        width: 30%;
        background: #5858FA;
        background-color: white;
        padding: 40px;
        border-radius: 10px;
        margin: 50px auto;
        display: block;
    }

    textarea {
        border-radius: 5px;
        resize: none;
        outline: none;
        min-width: 100%;
        height: 100px;
        border: 1px solid #A9A9A9;
        padding: 12px 40px 12px 20px;
    }
        textarea::placeholder {
            color: white;
        }

        textarea:focus, textarea:focus::placeholder, textarea:focus + i {
            color: #ff1464;
        }
    .glyphicon-remove-circle:hover {
        background-color: black;
        border-radius: 10px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {

        $("#image").change(function () {
            $("#hinhanh").remove();
            var anh = $("#image").get(0);
            $("#anh").before("<img src=" + URL.createObjectURL(anh.files[0]) + " height='100' style='border-radius:10px;' id='hinhanh' /><br />");

        });

    });
    function uploadimageclass(){
        $("#image").trigger("click");
    }


</script>

<div class="frameaccount">

    

    <div class="account">
        @using (Html.BeginForm("Checkeditclass", "Class", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div style=" background-image: linear-gradient(60deg, #5858FA, #081C46); position: relative; width: 90%; right: 20px; left: 20px; top: -60px; border-radius: 5px; text-align: left; padding: 20px"><label style="color:white">Edit Class</label><br /><label style="color:white">Complete your Class</label></div>



            <div class="form-group bmd-form-group" style="margin-top:-40px">
                <label class="bmd-label-floating" style="color:white">Class Name</label><br />

                @Html.TextAreaFor(model => model.TenLop, new { @class = "text1", @autofocus = "autofocus", placeholder = "Class Name", @required = "required" })<br />

            </div>

            <div class="form-group bmd-form-group">
                <label class="bmd-label-floating"  style="color:white">Class information</label><br />
                @Html.TextAreaFor(model => model.ThongTinLopHoc, new { @class = "text2", @autofocus = "autofocus", placeholder = "Class information ", @required = "required" })<br />
            </div>


            <div class="form-group bmd-form-group">

                <img src=@Model.Hinhanh  style="border-radius: 10px;max-width:100%;height:auto" id="hinhanh" onclick="uploadimageclass()" />
                <br />
                <input type="file" id="image" style="display:none;" accept=".png, .jpg, .jpeg" name="file" />
            </div>

            <div class="form-group bmd-form-group">
                <button type="submit" class="btn btn-primary ">Update Class</button>

            </div>



            @Html.ValidationMessage("Erroreditaccount", new { @class = "text-danger", @color = "red" })


        }

    </div>




</div>